name: bow
on:
   workflow_dispatch:
   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
             - name: run a command on bow console
               run: git clone https://github.com/discord/discord-example-app.git
